doc-warnings: yes
test-warnings: yes
strictness: veryhigh
autodetect: yes
max-line-length: 120
requirements:
    - requirements.txt
python-targets:
    - 3
pylint:
    run: true
    disable:
        - invalid-name 




